### ISSUE TITLE
ip: RTNETLINK answers: Not supported

### ISSUE THREAD

**Issue by a7i** [antoniaklja/kubewire#2]
Thank you for publishing this project. I am hoping to take it for a spin but am experiencing issues on EKS.

Here is the log message that I get:
```
Enabling IPv4 Forwarding
net.ipv4.conf.all.forwarding = 1
Generating server keys
40UDXqB3skeHwpZZnfymLncNCGRjMMe3MfZdHGX7FVE=
Configuring wireguard
ip: RTNETLINK answers: Not supported
```

Am I missing a configuration or pre-requisite? Thank you.

**Comment by antoniaklja** [comment]
@a7i have you installed `wireguard-dkms` and `wireguard-tools` packages on host?

**Comment by a7i** [comment]
@antoniaklja Yes. I am using EKS which is Amazon Linux 2.

I have included the following in userdata (for startup script).
```
curl -Lo /etc/yum.repos.d/wireguard.repo https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/epel-7/jdoss-wireguard-epel-7.repo
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum-config-manager --enable epel
yum install -y wireguard-dkms wireguard-tools
```

**Comment by antoniaklja** [comment]
thank you @a7i, I'll be rewriting implementation to Golang using https://blog.cloudflare.com/boringtun-userspace-wireguard-rust/ in the next weeks to give people full-fledged VPN on k8s. Stay tuned :)

**Comment by a7i** [comment]
Let me know if I can help, more than happy to.

**Comment by a7i** [comment]
@antoniaklja Just wanted to let you know that I have been able to get it to work on Amazon EKS (Amazon Linux 2).

I had to bootstrap the following to the host
```
curl -Lo /etc/yum.repos.d/wireguard.repo https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/epel-7/jdoss-wireguard-epel-7.repo
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum-config-manager --enable epel
yum install -y libmnl-devel @"Development tools" # netlink libraries
yum update -y # this will include kernel update as well, however kernel update does not update devel & tools
yum install -y kernel-devel-$(uname -r) kernel-tools-devel-$(uname -r) kernel-tools-$(uname -r)
yum install -y wireguard-dkms wireguard-tools
```

After running such scripts, we need to make sure that wireguard has been installed on host with the correct kernel headers which seems to be the case for me now.
```
$ uname -r
4.14.106-97.85.amzn2.x86_64
$ dkms status
wireguard, 0.0.20190406, 4.14.106-97.85.amzn2.x86_64, x86_64: installed
```

If dkms give the wrong kernel headers version or `wireguard, 0.0.20190406: added` without headers, that means that it hasn't been properly installed.

I am going to close this issue. Thanks for your support!
